# Generated by Django 4.2.7 on 2026-08-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMLArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Bootstrap icon class, e.g. bi-cpu', max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'AI/ML Area',
                'verbose_name_plural': 'AI/ML Areas',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Bootstrap icon or devicon class', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Learning Item',
                'verbose_name_plural': 'Currently Learning',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('fullstack', 'Full Stack'), ('aiml', 'AI / ML'), ('frontend', 'Frontend')], default='backend', max_length=20)),
                ('description', models.TextField(help_text='Short description shown on the card.')),
                ('long_description', models.TextField(help_text='Longer description shown in the details modal.')),
                ('technologies', models.CharField(help_text='Comma-separated list, e.g. Django, React, PostgreSQL', max_length=500)),
                ('features', models.TextField(blank=True, help_text='One feature per line.')),
                ('github', models.URLField(blank=True)),
                ('live', models.URLField(blank=True, help_text='Leave blank if no live demo.')),
                ('image', models.ImageField(blank=True, help_text='Upload a screenshot. Leave blank to use the placeholder.', null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower number = shown first.')),
                ('is_featured', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Database', 'Database'), ('Tools', 'Tools'), ('AI / ML', 'AI / ML')], default='Programming', max_length=30)),
                ('icon', models.CharField(help_text='Bootstrap icon or devicon class, e.g. bi-cpu or devicon-django-plain', max_length=100)),
                ('color', models.CharField(default='#3b82f6', help_text='Hex color for the icon.', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(help_text='e.g. 2023 or 2025–2026 or Current', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_current', models.BooleanField(default=False, help_text='Marks this entry as the current/active one.')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Timeline Entry',
                'verbose_name_plural': 'Timeline Entries',
                'ordering': ['order'],
            },
        ),
    ]
