# Generated by Django 4.2.7 on 2026-08-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload your resume PDF.', upload_to='resume/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one resume should be active at a time.')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resume',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
